apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: knative-kafka-sec-test
  labels:
    strimzi.io/cluster: kafka-sec
  namespace: amq-streams
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3