---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: kafka-broker-sec
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest