---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-broker-sec
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka 
  name: kafka-broker-sec
  namespace: kafka-broker-sec
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-sec-config
    namespace: knative-eventing