apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-sec-config
  namespace: knative-eventing
data:
  default.topic.partitions: "3"
  default.topic.replication.factor: "3"
  bootstrap.servers: "kafka-sec-kafka-bootstrap.amq-streams.svc.cluster.local:9092"
  auth.secret.ref.name: "kafka-sec-user"