---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: kafkasource-kafka-broker-app
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest