---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-channel-app
---
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafka-channel
  namespace: kafka-channel-app
spec:
  numPartitions: 3
  replicationFactor: 3

---

apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: hello-app-subs
  namespace: kafka-channel-app
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display