---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-broker-app
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka 
  name: kafka-broker-app
  namespace: kafka-broker-app
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config 
    namespace: knative-eventing