---
apiVersion: v1
kind: Namespace
metadata:
  name: apiserver-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sa
  namespace: apiserver-app 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-watcher
  namespace: apiserver-app 
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-ra-event-watcher
  namespace: apiserver-app 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-watcher
subjects:
  - kind: ServiceAccount
    name: events-sa
    namespace: apiserver-app

---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: testevents
  namespace: apiserver-app
spec:
  serviceAccountName: events-sa
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default

---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: apiserver-app
  labels:
    app.kubernetes.io/part-of: broker-app
spec: {}

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: apiserver-app
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
  namespace: apiserver-app
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
