---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-app-public-service
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-app-public
  namespace: hello-app-public-service
  labels:
    expose: route-public
spec:
  template:
    spec:
      containers:
      - image: quay.io/openshift-knative/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-app
  namespace: hello-app-public-service
spec:
  template:
    spec:
      containers:
      - image: quay.io/openshift-knative/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
