---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-app
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-app
  namespace: hello-app
spec:
  template:
    spec:
      containers:
      - image: quay.io/openshift-knative/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
