---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-app
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-app-traffic
  namespace: hello-app
spec:
  template:
    metadata:
      name: hello-app-traffic-v1
    spec:
      containers:
      - image: quay.io/openshift-knative/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
  traffic:
  - percent: 100
    revisionName: hello-app-traffic-v1
    tag: stable