---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-app-test
  namespace: kafka-broker-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-broker-app-test
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kafka-broker-app-test
    spec:
      containers:
        - name: kafka-broker-app-test
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/sh
            - -c
            - while true; do sleep 20; done